---
title             : "Are all errors created equal?"
shorttitle        : "Types of errors"

author: 
  - name          : "Sven Lesche"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Im Neuenheimer Feld 695"
    email         : "sven.lesche@stud.uni-heidelberg.de"
    # role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
    #   - "Conceptualization"
    #   - "Writing - Original Draft Preparation"
    #   - "Writing - Review & Editing"
  # - name          : "Author 2"
  #   affiliation   : "2"
  #   role:
  #     - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Ruprecht-Karls-University Heidelberg"
  # - id            : "2"
  #   institution   : "Konstanz Business School"
  # # add a second id using this syntax

authornote: |
  This is a research proposal completed for the seminar 'FOV Elektrophysiologie'. It was completed using R-markdown, all code needed to replicate this work can be found at https://github.com/SLesche/eeg-seminar. 

# abstract: |
#   One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
#   
#   Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
#   
#   One sentence clearly stating the **general problem** being addressed by  this particular study.
#   
#   One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
#   
#   Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
#   
#   One or two sentences to put the results into a more **general context**.
#   
#   Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
#   
#   <!-- https://tinyurl.com/ybremelq -->
#   
# keywords          : "keyword, more keyword, crazy keyword"
# wordcount         : "X"

bibliography      : ["lib.bib"] # put your ref files here

floatsintext      : yes # for pics in text
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no
link-citations    : true # custom addin, makes citations link to reference section
# figsintext        : yes # custom addin

classoption       : "man"
# the settings below allow compilation of APA7 style citations/documents
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - | 
    \raggedbottom
  - |
    \usepackage{hhline}
  - |
    \setlength{\parskip}{0pt}

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
output            : papaja::apa6_pdf
---
```{r setup, include = FALSE}
# Working directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# disallow tables breaking over pages
knitr::opts_chunk$set(ft.keepnext = TRUE,
                      ft.align = "left",
                      ft.latex.float = "float")
# Seed for random number generation
set.seed(1234)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed) # this adds random seed to all chunks
knitr::opts_chunk$set(autodep = TRUE)
knitr::dep_auto()
```
## Introduction
Post-error slowing (PES) describes the increase in response time (RT) on trials following an error compared to trials following a correct response. PES has been observed in a variety of experimental settings and is often accompanied by a post-error change in accuracy (PEA). Some studies observed decreased accuracy following errors while others find accuracy improvements. This has lead researchers to investigate differences in cognitive processes underlying post-error effects.

@damaso2020 have argued that different types of errors can lead to different types of post-error changes in behavior. They differentiate between _response speed_ and _evidence quality_ errors. 

@damaso2020 used median splits in RT to show that behavioral differences within-task exist between the two types. They observed increased PES for the faster bin of errors and post-error speeding for the bin containing mainly _evidence quality_ errors. Only measuring RT and accuracy changes provides a limited view of post-error effects and fails to capture differences in cognitive processes following the different types of errors. This RT approach is also highly susceptible to regression to the mean. We will aim to improve on the research design of @damaso2020 by adding two tasks each eliciting either _response speed_ or _evidence quality_ errors and using neurocognitive measures to measure post-error changes in cognitive processes. 

We will deploy three tasks designed to elicit either mainly _response speed_ errors, _evidence quality_ errors or both. A modified Flanker task will be used to elicit both error types. A modified version of the Behavioral Adaptation Task [@hester2007post] will be used to elicit mainly _response speed_ errors and a difficult color discrimination task [@buzzell2017error] will be used to elicit mainly _evidence quality_ errors.

Differences in post-error adjustments to cognitive processes will be studied in several measurements obtained in an electroencephalogram (EEG). This includes error-related components in event-related potentials (ERP), the _error-related negativity_ (ERN) and _error-positivity_ (Pe). <!-- We will also investigate the impact of errors on alpha power.  -->
ERN is a fronto-central negative deflection in the response-locked ERP that is more negative following error responses. It peaks around 100 ms after the response and is often associated with error monitoring or response conflict [@botvinick2001conflict].
Pe on the other hand is a centro-parietal positive deflection around 200 - 400 ms following the response. The functional interpretation of this component is less clear. It seems to be a later stage of error processing relevant for error awareness [@di2018errors].
<!-- Alpha waves are rhythmic oscillations between 8-13Hz reflecting low mental arousal [@niedermeyer2005]. @carp2009 observed reduced alpha power following errors, implying that changes in post-error behavior are influenced by increased cortical arousal. -->

Of interest in this study are differences in post-error adjustments between conditions containing either mainly _response speed_ or _evidence quality_ errors. We will obtain EEG measures and investigate post-error changes using t-tests. We predict post-error changes in behavior of all types to be more pronounced following _response speed_ errors. Errors due to poor evidence quality should not induce large changes in cognitive processes, as the underlying cognitive processes were not at fault when committing the error.

## Hypotheses
H1: Post-error slowing is more pronounced in conditions containing mainly _response speed_ errors.

H2: ERN is more negative in conditions containing mainly _response speed_ errors.

H3: Pe is more positive in conditions containing mainly _response speed_ errors.

## Design
### Participants
To detect a medium sized difference ($d > 0.50$) between post-error behavior depending on error type (evidence quality vs. response speed) in a t-test for dependent measures with $\alpha = 0.05$ and $\beta = 0.80$ we require a minimum of 27 participants [@faul2009statistical]. To account for potential removal of participants due to bad data quality, a minimum of 30 participants should be collected.

### Materials
**Flanker Task.** Participants have to decide whether the centrally presented letter is a "U" or a "V". This central letter is surrounded by flanking letters that either show the same letter (congruent) or the respective other letter (incongruent). This task elicits both _evidence quality_ and _response speed_ errors. We will determine the type of error via the RT of the error in a manner similar to @damaso2020. Participants will complete 5 blocks of 100 trials each.

**Behavioral Adaptation Task.** The stimuli "X" and "Y" are presented in a mostly alternating fashion. When the current stimulus is different from the previously presented stimulus, participants have to press the button corresponding to the stimulus. When the stimulus is repeated, participants should give no response at all. This leads to a large number of _response speed_ errors. Participants will complete 6 blocks of 250 trials each.

**Color Discrimination Task.** A stimulus consistent of a smaller circle surrounded by a bigger circle is presented each trial. The participant has to decide whether the inner circle is of the same color as the outer ring. The true difference in colors in incongruent stimuli will be adapted to each participant to ensure error rates of 20%. Errors in this task are mainly due to participants being unsure of whether there is a true difference and thus compromise largely _evidence quality_ errors. Participants will complete 8 blocks of 80 trials each.

### Procedure
We will conduct all tasks on one measurement occasion. We will counterbalance the order of the three tasks across participants. All tasks are two-choice tasks, appropriate button responses will be counterbalanced across participants. We will set the response-stimulus interval (RSI) to randomly vary between 800 ms and 1000 ms on each trial of all tasks. This aims to reduce anticipation effects and obtain clearer ERPs. All stimuli will be presented for 250ms. All trials have a response deadline of 2000ms. A fixation cross will be presented during the RSI. No feedback will be given outside of practice sessions. 

### EEG
As we will not conduct any spatial analysis and are mainly looking at ERPs, the quality and placement system of the electrodes does not need to be ideal. An example setup is given here, a lower number of electrodes or a different cap-style will not diminish the results obtained.

EEG will be recorded using 64 in-cap Ag/AgCl electrodes placed in the extended 10-20 system. Electrooculogram (EOG) measures will be taken bipolarly by two electrode placed above and below the left eye to correct for ocular artifacts. All impedances will be kept below 5 $k\Omega$. EEG signal will be recorded with a sampling rate of 1000 Hz (band-pass 0.1 Hz - 100 Hz) and referenced to an in-cap reference located between electrodes Cz and CPz and an in-cap ground just anterior to Fz. 

Following data aquisition, we will apply a low-pass filter of 16 Hz and a high-pass filter of 0.1 Hz. The raw data will be down-sampled to 250 Hz. To remove artifacts we will conduct an ICA on the dataset down-sampled to 100 Hz and passed through an additional high-pass filter of 1 Hz. Raw data will be cleaned by removing channels with unusually long flatlines, artifact-rates or line-noise. Channels removed will be interpolated following this procedure. EEG-data will be re-referenced to the average across electrodes and epoched to 200ms prior to and 1000ms following all stimulus and response markers.

Peak-amplitude of the response-locked ERN will be determined at the electrode Cz between 20 - 150 ms following the response. Response-locked peak amplitude of Pe will be measured at the Pz between 200 - 500 ms following the response.

## Analysis
The effect of error type on behavioral measures, ERN and Pe we be compared within the Flanker task and between the BAT and color discrimination task. We will define the trials surrounding the 25% fastest errors as belonging to the _response speed_ category and the trials surrounding the 75% slowest errors as belonging to the _evidence quality_ category in the flanker task. In the BAT, the 85% fastest errors will be termed _response speed_. The opposite is true for the color discrimination task, here the 85% slowest errors will be termed _evidence quality_. We will then obtain behavioral and electrophysiological measures for those categories and use t-tests to investigate differences in dependent measures between the two error types.

## Limitations
This study aims to falsify the concept of a unitary PES as a dependent measure often used in clinical research. We want to show that post-error adjustments differ depending on the type of error committed. We have identified several limitations.

Firstly, the comparison across tasks does not allow differences in post-error behavioral and neurocognitive to be mapped onto differences in error types. The inclusion of the Flanker task aims to combat this. Nonetheless, the overarching aim of this study is to falsify the assumption of a unitary PES-mechanism. Differences across tasks in neurocognitive behavior following errors also achieve this goal.

A possible limitation is the definition of errors used here. The fastest 25% of errors in the flanker task may not exclusively be _response speed_ errors. In order to combat this, we introduced two tasks that elicit mainly one of the error types. We will also pre-test the tasks and question participants regarding the reasons for error commission to ensure that our assumptions about the types of errors committed reflect reality.

A further limitation haunting PES research is the number of trials. Even with a minimum of 500 trials in each task, some participants may commit fewer than 10 errors. Higher trial counts and extensive pre-testing will be required to find an appropriate amount of trials per task. This is especially relevant when aiming to investigate ERP components on an individual level. @luck2005ten recommends a minimum of 30 trials even for large components. This may prove to be an issue here.

Despite these limitations, our study will allow us to investigate the presence and effect of two different error types. This will further add to recent findings illuminating the diverse nature of post-error adjustments in behavior and warn future researchers not to consider all post-error adjustments as equal.

<!-- References -->
\newpage
# References
::: {#refs custom-style="Bibliography"}
:::

