function [fitresult, gof] = createFit(ga_times, ga_value_1)
%CREATEFIT(GA_TIMES,GA_VALUE_1)
%  Create a fit.
%
%  Data for 'test_fit' fit:
%      X Input: ga_times
%      Y Output: ga_value_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Mar-2023 09:38:28


%% Fit: 'test_fit'.
[xData, yData] = prepareCurveData( ga_times, ga_value_1 );

% Set up fittype and options.
ft = fittype( 'sin8' );
excludedPoints = (xData < -200) | (xData > 1000);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [2.78956689150363 0.00262674971035936 0.203059811875574 1.50158697384391 0.0105069988414374 -2.4035677802163 0.875809407618277 0.0157604982621562 1.12766971387387 0.493251094077312 0.0210139976828749 -0.627637052683817 0.935633382156758 0.00525349942071872 -2.71770032443956 0.40975021035791 0.0577884936279059 -0.175957484920828 0.351045759172128 0.0315209965243123 2.49497679477552 0.301385110367705 0.0525349942071872 0.824931511595569];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Extract params


